name: Deploy to S3

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Astro
        run: npm run build --if-present
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist